/*
 * mini-cp is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License  v3
 * as published by the Free Software Foundation.
 *
 * mini-cp is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY.
 * See the GNU Lesser General Public License  for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with mini-cp. If not, see http://www.gnu.org/licenses/lgpl-3.0.en.html
 *
 * Copyright (c)  2018. by Laurent Michel, Pierre Schaus, Pascal Van Hentenryck
 */

package minicpbp.search;

import minicpbp.engine.core.IntVar;
import minicpbp.engine.core.Solver;
import minicpbp.state.StateManager;
import minicpbp.util.Procedure;
import minicpbp.util.exception.InconsistencyException;

import java.util.*;
import java.util.function.Predicate;
import java.util.stream.Collectors;

import static minicpbp.cp.BranchingScheme.selectMin;

/**
 * Belief-based Las-Vegas implementation
 */
public class LVSearch extends Search{

    private final Solver solver;
    private final IntVar[] x;

    private final List<Procedure> solutionListeners = new LinkedList<>();
    private final List<Procedure> failureListeners = new LinkedList<>();

    public LVSearch(Solver solver, IntVar[] x) {
        this.solver = solver;
        this.x = x;

        for(IntVar a: x)
            a.setForBranching(true);
        if(solver.getWeighingScheme() == Solver.ConstraintWeighingScheme.ARITY) {
            solver.computeMinArity();
        }
    }

    /**
     * Adds a listener that is called on each solution.
     *
     * @param listener the closure to be called whenever a solution is found
     */
    public void onSolution(Procedure listener) {
        solutionListeners.add(listener);
    }

    /**
     * Adds a listener that is called whenever a failure occurs
     * and the search backtracks.
     * This happensthat when a {@link InconsistencyException} is thrown
     * when executing the closure generated by the branching.
     *
     * @param listener the closure to be called whenever a failure occurs and
     *                 the search need to backtrack
     */
    public void onFailure(Procedure listener) {
        failureListeners.add(listener);
    }

    private void notifySolution() {
        solutionListeners.forEach(Procedure::call);
    }

    private void notifyFailure() {
        failureListeners.forEach(Procedure::call);
    }

    private SearchStatistics solve(SearchStatistics statistics, Predicate<SearchStatistics> limit) {
        lasVegas(statistics, limit);
        return statistics;
    }

    public SearchStatistics solve() {
        SearchStatistics statistics = new SearchStatistics();
        return solve(statistics, stats -> false);
    }

    public SearchStatistics solve(Predicate<SearchStatistics> limit) {
        SearchStatistics statistics = new SearchStatistics();
        return solve(statistics, limit);
    }

    private SearchStatistics solveRestarts(SearchStatistics statistics, Predicate<SearchStatistics> limit, int nbFailsCutoff, final double restartFactor) {
        int cutoff = nbFailsCutoff;
        final int[] cumulCutoff = new int[]{cutoff};
        while (!limit.test(statistics)) {
            Predicate<SearchStatistics> restartLimit = limit.or(stat -> stat.numberOfFailures() > cumulCutoff[0]);
            lasVegas(statistics, restartLimit);
            cutoff *= (int) restartFactor;
            cumulCutoff[0] += cutoff;
        }
        return statistics;
    }

    public void initializeImpact(IntVar... x) {
        throw new UnsupportedOperationException("Las-Vegas Search does not support impact");
    }

    public void initializeImpactDomains(IntVar... x) {
        throw new UnsupportedOperationException("Las-Vegas Search does not support impact");
    }


    /**
     * Effectively start a depth first search with restarts
     * looking for every solution.
     *
     * @return an object with the statistics on the search
     */
    public SearchStatistics solveRestarts() {
        SearchStatistics statistics = new SearchStatistics();
        return solveRestarts(statistics, stats -> false, 100, 1.5);
    }

    /**
     * Effectively start a depth first search with restarts
     * with a given predicate called at each node
     * to stop the search when it becomes true.
     *
     * @param limit a predicate called at each node
     *             that stops the search when it becomes true
     * @return an object with the statistics on the search
     */
    public SearchStatistics solveRestarts(Predicate<SearchStatistics> limit) {
        SearchStatistics statistics = new SearchStatistics();
        return solveRestarts(statistics, limit, 100, 1.5);
    }
    public SearchStatistics solveRestarts(SearchStatistics statistics, Predicate<SearchStatistics> limit) {
        return solveRestarts(statistics, limit, 100, 1.5);
    }

    public SearchStatistics solveRestarts(Predicate<SearchStatistics> limit, int nbFailCutoff, double restartFactor) {
        SearchStatistics statistics = new SearchStatistics();
        return solveRestarts(statistics, limit, nbFailCutoff, restartFactor);
    }

    public SearchStatistics optimize(Objective obj, Predicate<SearchStatistics> limit) {
        throw new UnsupportedOperationException("Las-Vegas Search does not support optimisation");
    }


    private void lasVegas(SearchStatistics statistics, Predicate<SearchStatistics> limit) {
        solver.getStateManager().withNewState(() -> {
            if (limit.test(statistics))
                throw new StopSearchException();

            solver.fixPoint();
            solver.vanillaBP(2);
            for (int i = 0; i < x.length; i++) {
                IntVar xs = selectMin(x,
                        xi -> xi.size() > 1,
                        IntVar::entropy);

                if (xs != null) {
                    try {
                        statistics.incrNodes();
                        int v = xs.biasedWheelValue();
                        xs.assign(v);
                        solver.fixPoint();
                        solver.vanillaBP(2);
                    } catch (InconsistencyException e) {
                        statistics.incrFailures();
                        notifyFailure();
                        return;
                    }
                } else {
                    statistics.incrSolutions();
                    notifySolution();
                    return;
                }
            }
        });
    }

    private Optional<IntVar> biasedWheelVariable() {
        if (x.length == 0) {
            throw new NoSuchElementException();
        }
        Random rand = solver.getRandomNbGenerator();

        List<IntVar> candidates = Arrays.stream(x).filter(xi -> xi.size() > 1).collect(Collectors.toList());
        Optional<Double> max = candidates.stream().map(xi -> 1/xi.entropy()).max(Double::compareTo);

        if (!max.isPresent()) {
            return Optional.empty();
        }

        while (true) {
            IntVar xi = candidates.get(rand.nextInt(candidates.size()));
            if (rand.nextDouble() < 1/(xi.entropy() * max.get()))
                return Optional.of(xi);
        }
    }
}
